# Generated by Django 3.2.5 on 2021-08-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_create',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
